### ISSUE TITLE
Visma name is used in the domain and no warning of security risks on login

### ISSUE THREAD

**Issue by vasilyulianko-visma** [theodorklauritzen/VismaCalendar#16]
Hi Theodor, nice job. Visma InSchool mobile team has another reason to speed up!

A couple of things I would like to ask you to do - remove Visma company name from the domain name (it may raise legal concerns) and add a warning of security risks for the users to the login page. Please, think of the less computer-savvy users who use their credentials in your app.

Vasily Ulianko, director of engineering @ Visma InSchool.

**Comment by theodorklauritzen** [comment]
I'll have a look at it
